// Official Lithuanian cities and municipality centres.
// Covers all 60 municipalities plus major towns commonly used by service providers.
export const LT_CITIES = [
  "Vilnius",
  "Kaunas",
  "Klaipėda",
  "Šiauliai",
  "Panevėžys",
  "Alytus",
  "Marijampolė",
  "Mažeikiai",
  "Jonava",
  "Utena",
  "Kėdainiai",
  "Telšiai",
  "Tauragė",
  "Ukmergė",
  "Visaginas",
  "Plungė",
  "Kretinga",
  "Palanga",
  "Šilutė",
  "Radviliškis",
  "Rokiškis",
  "Druskininkai",
  "Elektrėnai",
  "Biržai",
  "Anykščiai",
  "Lentvaris",
  "Naujoji Akmenė",
  "Prienai",
  "Joniškis",
  "Kelmė",
  "Varėna",
  "Kaišiadorys",
  "Pasvalys",
  "Zarasai",
  "Kupiškis",
  "Skuodas",
  "Molėtai",
  "Šilalė",
  "Šalčininkai",
  "Širvintos",
  "Ignalina",
  "Švenčionys",
  "Trakai",
  "Kalvarija",
  "Kazlų Rūda",
  "Vilkaviškis",
  "Šakiai",
  "Jurbarkas",
  "Raseiniai",
  "Pakruojis",
  "Nida",
  "Neringa",
  "Rietavas",
  "Birštonas",
  "Lazdijai",
  "Pagėgiai",
  "Grigiškės",
  "Gargždai",
  "Garliava",
  "Salantai",
  "Kavarskas",
  "Vievis",
] as const;

export type LtCity = (typeof LT_CITIES)[number];

export function isLtCity(v: string | null | undefined): v is LtCity {
  return !!v && (LT_CITIES as readonly string[]).includes(v);
}
