export type UiLanguage = "lt" | "en" | "ru";

const en: Record<string, string> = {
  "Mano valdymas": "My workspace", "Naršyti": "Explore", "Papildomos paslaugos": "Extra services",
  "Informacija ir pagalba": "Information & help", "Kita": "Other", "Apžvalga": "Overview",
  "Kalendorius ir vizitai": "Calendar & appointments", "Mano kalendorius ir vizitai": "My calendar & appointments",
  "Rezervacijos": "Bookings", "Mano rezervacijos": "My bookings", "Klientų bazė (CRM)": "Client database (CRM)",
  "Salono informacija ir meniu": "Salon information & menu", "Profilis ir paslaugų meniu": "Profile & services",
  "Paslaugų meniu": "Service menu", "Komanda ir darbuotojai": "Team & staff", "Skelbimai": "Classifieds",
  "Mano skelbimai": "My classifieds", "Ieškomi modeliai": "Models wanted", "Mokymai ir seminarai": "Training & seminars",
  "Tiekėjų pasiūlymai": "Supplier offers", "Tiekėjų pasiūlymai verslui": "Supplier offers for businesses",
  "Profesionalų bendruomenė": "Professional community", "Modelių paieška": "Model search",
  "Mokymų skelbimas ir straipsniai": "Training listings & articles", "Reklama ir straipsniai": "Advertising & articles",
  "Patalpų nuoma": "Premises rental", "Nuomos užklausos": "Rental enquiries", "Renginiai": "Events",
  "Narystė": "Membership", "Piniginė": "Wallet", "Patikrinimas": "Verification", "Produktai": "Products",
  "Mano pasiūlymai": "My offers", "Seminarai": "Seminars", "Įmonės informacija": "Company information",
  "Reklaminiai straipsniai ir baneriai": "Sponsored articles & banners", "Mokykla ir kursai": "School & courses",
  "Mokymų registracijos": "Training registrations", "Banerinė reklama ir straipsniai": "Banner ads & articles",
  "Specialūs pasiūlymai": "Special offers", "Aktualijos / Straipsniai": "News / Articles",
  "Individualūs meistrai": "Independent professionals", "Salonai": "Salons", "Prekiniai ženklai": "Brands",
  "Tapk grožio srities specialistu": "Become a beauty professional", "Pagalba ir susisiekimas": "Help & contact",
  "DUK": "FAQ", "Apie mus": "About us", "Privatumo politika": "Privacy policy",
  "Profilis ir nustatymai": "Profile & settings", "Pranešimai": "Notifications", "Svetainės redaktorius": "Site editor",
  "Atsarginės kopijos": "Backups", "Transliacijos": "Broadcasts", "Dovanojimai": "Grants", "Finansai": "Finance",
  "Visi salonų profiliai": "All salon profiles", "Visi meistrų profiliai": "All professional profiles",
  "Akcijos ir nuolaidos": "Deals and discounts", "Naujienos ir tendencijos": "News and trends",
  "Profesionali kosmetika": "Professional cosmetics", "Mokyklų ir kursų sąrašas": "Schools and courses",
  "Vizitų valdymas": "Manage appointments", "Paslaugų valdymas": "Manage services",
  "Pasiūlymai profesionalams": "Offers for professionals", "Reklama platformoje": "Advertising on the platform",
  "Produktų katalogas": "Product catalogue", "Profilis ir kontaktai": "Profile and contacts",
  "Planas ir mokėjimai": "Plan and payments", "Kursų valdymas": "Manage courses", "Dalyvių sąrašai": "Participant lists",
  "Nuoma · pardavimai · darbas": "Rentals · sales · jobs", "Skelbimų valdymas": "Manage classifieds",
  "Programėlės meniu": "App menu", "Valdymas, paslaugos ir paskyros nustatymai": "Workspace, services and account settings",
  "Programėlės skiltys": "App sections", "Žiūrėti savo profilį": "View your profile", "Prisijungti": "Sign in",
  "Atsijungti": "Sign out", "Sukurti paskyrą": "Create account", "Prisijunkite": "Sign in",
  "Norėdami matyti išskirtinius pasiūlymus bei nuolaidas, prisijunkite arba susikurkite nemokamą paskyrą.": "Sign in or create a free account to see exclusive offers and discounts.",
  "Registruotis": "Sign up", "Atverti meniu": "Open menu", "Užverti": "Close",
  "Skelbimų paketai": "Classified packages", "Nuo €0.99 už skelbimą": "From €0.99 per listing",
  "Banerio reklama 3–30 d.": "Banner advertising for 3–30 days", "Mokymai, seminarai ir modelių paieška": "Training, seminars & model search",
  "Vienkartinis paskelbimas": "Single publication", "7, 14, 21 d. arba mėnesiui": "7, 14, 21 days or one month",
  "Pasiūlymai grožio profesionalams": "Offers for beauty professionals", "Naršyti tiekėjų pasiūlymus": "Browse supplier offers",
  "Patvirtinkite užsakymą": "Confirm order", "Atšaukti": "Cancel", "Apmokėti išsaugota kortele": "Pay with saved card",
  "Procedūros modeliams": "Procedures for models", "Miestas (nebūtina)": "City (optional)", "Visi miestai": "All cities",
  "Kategorija": "Category", "Pasirinkite kategoriją": "Choose a category", "Ieškoti kategorijos...": "Search categories...",
  "Kam skirtas kirpimas ar procedūra?": "Who is the haircut or procedure for?", "Paslauga": "Service",
  "Pirmiausia pasirinkite kategoriją": "Choose a category first", "Pasirinkite, kam skirta paslauga": "Choose who the service is for",
  "Ieškoti konkrečios paslaugos...": "Search for a specific service...", "Šioje kategorijoje paslaugų nerasta.": "No services found in this category.",
  "Ieškai konkretaus prekinio ženklo?": "Looking for a specific brand?", "Paieška pagal prekinį ženklą": "Search by brand",
  "Visi": "All", "Naujienos": "News", "Tendencijos": "Trends", "Patarimai": "Tips", "Valdymas": "Workspace",
  "Profilis ir paskyra": "Profile & account", "Paskyra": "Account",
  "Ieško modelio": "Models wanted", "Meistrai": "Professionals", "Mokymai": "Training",
  "Specialūs mėnesio pasiūlymai profesionalams": "Monthly offers for professionals", "Tik grožio verslams": "Beauty businesses only",
  "Tiekėjai / vadyba": "Suppliers / management", "Produktai ir tiekėjai": "Products and suppliers",
  "Mokymai / seminarai": "Training / seminars", "Profesionalų kalendorius": "Professional calendar",
  "Grožio industrijos skelbimai": "Beauty industry classifieds",
};

const ru: Record<string, string> = {
  "Mano valdymas": "Моё управление", "Naršyti": "Обзор", "Papildomos paslaugos": "Дополнительные услуги",
  "Informacija ir pagalba": "Информация и помощь", "Kita": "Другое", "Apžvalga": "Обзор",
  "Kalendorius ir vizitai": "Календарь и визиты", "Mano kalendorius ir vizitai": "Мой календарь и визиты",
  "Rezervacijos": "Записи", "Mano rezervacijos": "Мои записи", "Klientų bazė (CRM)": "База клиентов (CRM)",
  "Salono informacija ir meniu": "Информация о салоне и меню", "Profilis ir paslaugų meniu": "Профиль и услуги",
  "Paslaugų meniu": "Меню услуг", "Komanda ir darbuotojai": "Команда и сотрудники", "Skelbimai": "Объявления",
  "Mano skelbimai": "Мои объявления", "Ieškomi modeliai": "Ищут моделей", "Mokymai ir seminarai": "Обучение и семинары",
  "Tiekėjų pasiūlymai": "Предложения поставщиков", "Tiekėjų pasiūlymai verslui": "Предложения поставщиков для бизнеса",
  "Profesionalų bendruomenė": "Сообщество профессионалов", "Modelių paieška": "Поиск моделей",
  "Mokymų skelbimas ir straipsniai": "Обучение и статьи", "Reklama ir straipsniai": "Реклама и статьи",
  "Patalpų nuoma": "Аренда помещений", "Nuomos užklausos": "Запросы на аренду", "Renginiai": "События",
  "Narystė": "Подписка", "Piniginė": "Кошелёк", "Patikrinimas": "Проверка", "Produktai": "Продукты",
  "Mano pasiūlymai": "Мои предложения", "Seminarai": "Семинары", "Įmonės informacija": "Информация о компании",
  "Reklaminiai straipsniai ir baneriai": "Рекламные статьи и баннеры", "Mokykla ir kursai": "Школа и курсы",
  "Mokymų registracijos": "Регистрации на обучение", "Banerinė reklama ir straipsniai": "Баннерная реклама и статьи",
  "Specialūs pasiūlymai": "Специальные предложения", "Aktualijos / Straipsniai": "Новости / Статьи",
  "Individualūs meistrai": "Частные мастера", "Salonai": "Салоны", "Prekiniai ženklai": "Бренды",
  "Tapk grožio srities specialistu": "Станьте специалистом красоты", "Pagalba ir susisiekimas": "Помощь и контакты",
  "DUK": "Частые вопросы", "Apie mus": "О нас", "Privatumo politika": "Политика конфиденциальности",
  "Profilis ir nustatymai": "Профиль и настройки", "Pranešimai": "Уведомления", "Svetainės redaktorius": "Редактор сайта",
  "Atsarginės kopijos": "Резервные копии", "Transliacijos": "Рассылки", "Dovanojimai": "Подарки", "Finansai": "Финансы",
  "Visi salonų profiliai": "Все профили салонов", "Visi meistrų profiliai": "Все профили мастеров",
  "Akcijos ir nuolaidos": "Акции и скидки", "Naujienos ir tendencijos": "Новости и тенденции",
  "Profesionali kosmetika": "Профессиональная косметика", "Mokyklų ir kursų sąrašas": "Школы и курсы",
  "Vizitų valdymas": "Управление визитами", "Paslaugų valdymas": "Управление услугами",
  "Pasiūlymai profesionalams": "Предложения для профессионалов", "Reklama platformoje": "Реклама на платформе",
  "Produktų katalogas": "Каталог продуктов", "Profilis ir kontaktai": "Профиль и контакты", "Planas ir mokėjimai": "План и платежи",
  "Kursų valdymas": "Управление курсами", "Dalyvių sąrašai": "Списки участников",
  "Nuoma · pardavimai · darbas": "Аренда · продажи · работа", "Skelbimų valdymas": "Управление объявлениями",
  "Programėlės meniu": "Меню приложения", "Valdymas, paslaugos ir paskyros nustatymai": "Управление, услуги и настройки аккаунта",
  "Programėlės skiltys": "Разделы приложения", "Žiūrėti savo profilį": "Открыть профиль", "Prisijungti": "Войти",
  "Atsijungti": "Выйти", "Sukurti paskyrą": "Создать аккаунт", "Prisijunkite": "Войдите",
  "Norėdami matyti išskirtinius pasiūlymus bei nuolaidas, prisijunkite arba susikurkite nemokamą paskyrą.": "Войдите или создайте бесплатный аккаунт, чтобы видеть эксклюзивные предложения и скидки.",
  "Registruotis": "Регистрация", "Atverti meniu": "Открыть меню", "Užverti": "Закрыть",
  "Skelbimų paketai": "Пакеты объявлений", "Nuo €0.99 už skelbimą": "От €0.99 за объявление",
  "Banerio reklama 3–30 d.": "Баннерная реклама на 3–30 дней", "Mokymai, seminarai ir modelių paieška": "Обучение, семинары и поиск моделей",
  "Vienkartinis paskelbimas": "Одно размещение", "7, 14, 21 d. arba mėnesiui": "7, 14, 21 день или месяц",
  "Pasiūlymai grožio profesionalams": "Предложения для профессионалов красоты", "Naršyti tiekėjų pasiūlymus": "Смотреть предложения поставщиков",
  "Patvirtinkite užsakymą": "Подтвердите заказ", "Atšaukti": "Отмена", "Apmokėti išsaugota kortele": "Оплатить сохранённой картой",
  "Procedūros modeliams": "Процедуры для моделей", "Miestas (nebūtina)": "Город (необязательно)", "Visi miestai": "Все города",
  "Kategorija": "Категория", "Pasirinkite kategoriją": "Выберите категорию", "Ieškoti kategorijos...": "Поиск категории...",
  "Kam skirtas kirpimas ar procedūra?": "Для кого стрижка или процедура?", "Paslauga": "Услуга",
  "Pirmiausia pasirinkite kategoriją": "Сначала выберите категорию", "Pasirinkite, kam skirta paslauga": "Выберите, для кого услуга",
  "Ieškoti konkrečios paslaugos...": "Найти конкретную услугу...", "Šioje kategorijoje paslaugų nerasta.": "В этой категории услуг не найдено.",
  "Ieškai konkretaus prekinio ženklo?": "Ищете конкретный бренд?", "Paieška pagal prekinį ženklą": "Поиск по бренду",
  "Visi": "Все", "Naujienos": "Новости", "Tendencijos": "Тенденции", "Patarimai": "Советы", "Valdymas": "Управление",
  "Profilis ir paskyra": "Профиль и аккаунт", "Paskyra": "Аккаунт",
  "Ieško modelio": "Ищут модель", "Meistrai": "Мастера", "Mokymai": "Обучение",
  "Specialūs mėnesio pasiūlymai profesionalams": "Ежемесячные предложения для профессионалов", "Tik grožio verslams": "Только для бьюти-бизнеса",
  "Tiekėjai / vadyba": "Поставщики / управление", "Produktai ir tiekėjai": "Продукты и поставщики",
  "Mokymai / seminarai": "Обучение / семинары", "Profesionalų kalendorius": "Календарь для профессионалов",
  "Grožio industrijos skelbimai": "Объявления индустрии красоты",
};

export function uiText(text: string, language?: string): string {
  const lang = (language?.split("-")[0] || "lt") as UiLanguage;
  if (lang === "en") return en[text] ?? text;
  if (lang === "ru") return ru[text] ?? text;
  return text;
}