ALTER TABLE public.site_content
  ADD COLUMN IF NOT EXISTS block_kind TEXT NOT NULL DEFAULT 'section',
  ADD COLUMN IF NOT EXISTS align TEXT NOT NULL DEFAULT 'left',
  ADD COLUMN IF NOT EXISTS style TEXT NOT NULL DEFAULT 'plain',
  ADD COLUMN IF NOT EXISTS is_custom BOOLEAN NOT NULL DEFAULT false;